# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
hub:
  image: 
    name: us-docker.pkg.dev/ai-on-gke/jupyterhub-authentication-class/jupyter-auth-class
    tag: latest
  config:
    JupyterHub:
      authenticator_class: ${authenticator_class}
    GCPIAPAuthenticator: 
      header_name: 'X-Goog-IAP-JWT-Assertion'
      project_id: '${project_id}'
      namespace: '${namespace}'
      service_name: '${service_name}'
      project_number: '${project_number}'
      # support legacy image
      expected_audience: '/projects/${project_number}/global/backendServices/${service_id}'
    Authenticator:
      admin_users:
        - user1
        - user2
      allowed_users:
        - user3
        - user4
    # ...
    DummyAuthenticator:
      password: ${password}
  networkPolicy:
    enabled: false
  
prePuller:
  hook:
    enabled: false

proxy:
  chp:
    networkPolicy:
      enabled: false
  service:
    type: ${service_type}
    annotations: 
      beta.cloud.google.com/backend-config: '{"default": "${backend_config}"}'
  traefik:
    networkPolicy:
      enabled: false

scheduling:
  userScheduler:
    enabled: false

singleuser:
  memory:
    limit: 32G
    guarantee: 8G
  cpu:
    limit: 8
    guarantee: 4
  extraResource:
    limits:
      ephemeral-storage: 20Gi
    guarantees:
      ephemeral-storage: 10Gi
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
# Used for GCSFuse to set the ephemeral storage as the home directory. If not set, it will show a permission error on the pod log when using GCSFuse. 
  extraEnv:
    JUPYTER_ALLOW_INSECURE_WRITES: "true"
  extraLabels:
    created-by: "jupyter-on-gke"
  image:
    name: jupyter/tensorflow-notebook
    tag: python-3.10
  startTimeout: 1000
  extraAnnotations:
    gke-gcsfuse/volumes: "true"
    gke-gcsfuse/cpu-limit: 500m
    gke-gcsfuse/memory-limit: 250Mi
    gke-gcsfuse/ephemeral-storage-limit: 10Gi
  serviceAccountName: ${k8s_service_account}
    # Configure csi for gcsfuse
  storage:
    dynamic:
      pvcNameTemplate: claim-{username}
    extraVolumes:
      - name: test-vol
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: ${gcs_bucket}
            mountOptions: "implicit-dirs,uid=1000,gid=100"
    extraVolumeMounts:
        - name: test-vol
          mountPath: /persist-data
# More info on kubespawner overrides: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner
#   profile example:
#   - display_name: "Learning Data Science"
#      description: "Datascience Environment with Sample Notebooks"
#      kubespawner_override:
#           cpu_limit: .5
#           cpu_guarantee: .5
#           mem_limit: 1G
#           mem_guarantee: 1G
#        image: jupyter/datascience-notebook:2343e33dec46
#        lifecycle_hooks:
#          postStart:
#            exec:
#              command:
#                - "sh"
#                - "-c"
#                - >
#                  gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
  profileList:
    - display_name: "CPU"
      description: "Creates CPU VMs as the compute for notebook execution."
      profile_options:
        storage:
          display_name: "Storage"
          choices:
            DefaultStorage:
              display_name: "DefaultStorage"
              kubespawner_override:
                default: true
            GCSFuse:
              display_name: "GCSFuse"
              kubespawner_override:
                volume_mounts:
                - name: gcs-fuse-csi-ephemeral
                  mountPath: /home/jovyan
                volumes:
                - name: gcs-fuse-csi-ephemeral
                  csi:
                    driver: gcsfuse.csi.storage.gke.io
                    volumeAttributes:
                      bucketName: gcsfuse-{username}
                      mountOptions: "uid=1000,gid=100,o=noexec,implicit-dirs,dir-mode=777,file-mode=777"
              node_selector:
                iam.gke.io/gke-metadata-server-enabled: "true"
      default: true
    - display_name: "TPU"
      description: "Creates TPUs VMs as the compute for notebook execution. Will only work if TPU is enabled."
      profile_options:
        storage:
          display_name: "Storage"
          choices:
            DefaultStorage:
              display_name: "DefaultStorage"
              kubespawner_override:
                default: true
            GCSFuse:
              display_name: "GCSFuse"
              kubespawner_override:
                volume_mounts:
                - name: gcs-fuse-csi-ephemeral
                  mountPath: /home/jovyan
                volumes:
                - name: gcs-fuse-csi-ephemeral
                  csi:
                    driver: gcsfuse.csi.storage.gke.io
                    volumeAttributes:
                      bucketName: gcsfuse-{username}
                      mountOptions: "uid=1000,gid=100,o=noexec,implicit-dirs,dir-mode=777,file-mode=777"
              node_selector:
                iam.gke.io/gke-metadata-server-enabled: "true"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:python-3.10
        extra_resource_limits:
          google.com/tpu: "4"
        node_selector:
          cloud.google.com/gke-tpu-accelerator: "tpu-v4-podslice"
          cloud.google.com/gke-tpu-topology: "2x2x1"
    - display_name: "GPU T4"
      description: "Creates GPU VMs (T4) as the compute for notebook execution"
      profile_options:
        storage:
          display_name: "Storage"
          choices:
            DefaultStorage:
              display_name: "DefaultStorage"
              kubespawner_override:
                default: true
            GCSFuse:
              display_name: "GCSFuse"
              kubespawner_override:
                volume_mounts:
                - name: gcs-fuse-csi-ephemeral
                  mountPath: /home/jovyan
                volumes:
                - name: gcs-fuse-csi-ephemeral
                  csi:
                    driver: gcsfuse.csi.storage.gke.io
                    volumeAttributes:
                      bucketName: gcsfuse-{username}
                      mountOptions: "uid=1000,gid=100,o=noexec,implicit-dirs,dir-mode=777,file-mode=777"
              node_selector:
                iam.gke.io/gke-metadata-server-enabled: "true"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:python-3.10
        extra_resource_limits:
          # number of gpus needed on the node
          nvidia.com/gpu: "2"
      #  possible values: nvidia-tesla-k80, nvidia-tesla-p100, nvidia-tesla-p4, nvidia-tesla-v100, nvidia-tesla-t4, nvidia-tesla-a100, nvidia-a100-80gb, nvidia-l4
        node_selector:
          cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    - display_name: "GPU A100"
      description: "Creates GPU VMs (A100) as the compute for notebook execution"
      profile_options:
        storage:
          display_name: "Storage"
          choices:
            DefaultStorage:
              display_name: "DefaultStorage"
              kubespawner_override:
                default: true
            GCSFuse:
              display_name: "GCSFuse"
              kubespawner_override:
                volume_mounts:
                - name: gcs-fuse-csi-ephemeral
                  mountPath: /home/jovyan
                volumes:
                - name: gcs-fuse-csi-ephemeral
                  csi:
                    driver: gcsfuse.csi.storage.gke.io
                    volumeAttributes:
                      bucketName: gcsfuse-{username}
                      mountOptions: "uid=1000,gid=100,o=noexec,implicit-dirs,dir-mode=777,file-mode=777"
              node_selector:
                iam.gke.io/gke-metadata-server-enabled: "true"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:python-3.10
        extra_resource_limits:
          nvidia.com/gpu: "2"
        # GPU requests 
        extra_resource_guarantees:
          nvidia.com/gpu: "2"
        node_selector:
          cloud.google.com/gke-accelerator: "nvidia-tesla-a100"
  cmd: null
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
