apiVersion: apps/v1
kind: Deployment
metadata:
  name: densenet161-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: densenet161-server
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
      labels:
        app: densenet161-server
    spec:
      serviceAccount: sax-sa
      nodeSelector:
        cloud.google.com/gke-tpu-topology: 1x1
        cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice # target version
      hostNetwork: false
      restartPolicy: Always
      containers:
      - name: mydensenet161
        image: us-docker.pkg.dev/cloud-tpu-images/inference/torchserve-tpu:v0.8.2-20230829
        ports:
        - containerPort: 7070
        - containerPort: 7071
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 8082
        - containerPort: 9001
        - containerPort: 9012
        volumeMounts:
          - mountPath: /home/model-server/
            name: densenet161-external-storage
            subPath: pytorch
            readOnly: true
        securityContext:
          privileged: true
        resources:
          requests:
            google.com/tpu: 1
          limits:
            google.com/tpu: 1
      volumes:
        - name: densenet161-external-storage
          persistentVolumeClaim:
            claimName: external-storage-pvc
            readOnly: true