# This file can update the JupyterHub Helm chart's default configuration values.
#
# For reference see the configuration reference and default values, but make
# sure to refer to the Helm chart version of interest to you!
#
# Introduction to YAML:     https://www.youtube.com/watch?v=cdLNKUoMc6c
# Chart config reference:   https://zero-to-jupyterhub.readthedocs.io/en/stable/resources/reference.html
# Chart default values:     https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/HEAD/jupyterhub/values.yaml
# Available chart versions: https://jupyterhub.github.io/helm-chart/
hub:
  config:
    Authenticator:
      admin_users:
        - user1
        - user2
      allowed_users:
        - user3
        - user4
    # ...
    DummyAuthenticator:
      password: password
    JupyterHub:
      authenticator_class: dummy
  networkPolicy:
    enabled: false

prePuller:
  hook:
    enabled: false

proxy:
  chp:
    networkPolicy:
      enabled: false
  traefik:
    networkPolicy:
      enabled: false

scheduling:
  userScheduler:
    enabled: false

singleuser:
  cpu:
    limit: .5
    guarantee: .5
  memory:
    limit: 1G
    guarantee: 1G
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
  image:
    name: jupyter/tensorflow-notebook
    tag: python-3.10
  startTimeout: 700
# More info on kubespawner overrides: https://jupyterhub-kubespawner.readthedocs.io/en/latest/spawner.html#kubespawner.KubeSpawner
#   profile example:
#   - display_name: "Learning Data Science"
#      description: "Datascience Environment with Sample Notebooks"
#      kubespawner_override:
#           cpu_limit: .5
#           cpu_guarantee: .5
#           mem_limit: 1G
#           mem_guarantee: 1G
#        image: jupyter/datascience-notebook:2343e33dec46
#        lifecycle_hooks:
#          postStart:
#            exec:
#              command:
#                - "sh"
#                - "-c"
#                - >
#                  gitpuller https://github.com/data-8/materials-fa17 master materials-fa;
  profileList:
    - display_name: "Profile1 name"
      description: "description here"
      default: true
    - display_name: "Profile2 name"
      description: "description here"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:python-3.10
        extra_resource_limits:
          # number of gpus needed on the node
          nvidia.com/gpu: "2"
      #  possible values: nvidia-tesla-k80, nvidia-tesla-p100, nvidia-tesla-p4, nvidia-tesla-v100, nvidia-tesla-t4, nvidia-tesla-a100, nvidia-a100-80gb, nvidia-l4
        node_selector:
          cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
    - display_name: "Profile3 name"
      description: "description"
      kubespawner_override:
        image: jupyter/tensorflow-notebook:python-3.10
        extra_resource_limits:
          nvidia.com/gpu: "2"
        # GPU requests 
        extra_resource_guarantees:
          nvidia.com/gpu: "2"
        node_selector:
          cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
  cmd: null
  cloudMetadata:
    blockWithIptables: false
  networkPolicy:
    enabled: false
